=== razzuSharma/xml_Projects/19031814_russiandoll.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="MedicalStore">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="Stock">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="Name" type="xs:string" />
                            <xs:element name="Address">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="Country" type="xs:string" />
                                        <xs:element name="City" type="xs:string" />
                                        <xs:element name="Street" type="xs:string" />
                                    </xs:sequence>
                                    <xs:attribute name="Continent" use="required" />
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="Contact">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="phoneNum">
                                            <xs:simpleType>
                                                <xs:restriction base="xs:string">
                                                    <xs:pattern value="98[0-9]{8}" />
                                                </xs:restriction>
                                            </xs:simpleType>
                                        </xs:element>
                                        <xs:element name="Email">
                                            <xs:simpleType>
                                                <xs:restriction base="xs:string">
                                                    <xs:pattern value="[^@]+@[^\.]+\..+" />
                                                </xs:restriction>
                                            </xs:simpleType>
                                        </xs:element>
                                    </xs:sequence>
                                    <xs:attribute name="CityCode" use="required" />
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="Logo" />
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="MedicineDetails" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="Medicine">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="Categories" type="xs:string" />
                                        <xs:element name="useType" type="xs:string" />
                                        <xs:element name="MedNames">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="Name">
                                                        <xs:complexType>
                                                            <xs:simpleContent>
                                                                <xs:extension base="xs:string">
                                                                    <xs:attribute name="namID" use="required" />
                                                                </xs:extension>
                                                            </xs:simpleContent>
                                                        </xs:complexType>
                                                    </xs:element>
                                                    <xs:element name="Manufacturer" type="xs:string" />
                                                    <xs:element name="SideEffects">
                                                        <xs:simpleType>
                                                            <xs:restriction base="xs:token">
                                                                <xs:enumeration value="YES" />
                                                                <xs:enumeration value="NO" />
                                                            </xs:restriction>
                                                        </xs:simpleType>
                                                    </xs:element>
                                                    <xs:element name="Availability">
                                                        <xs:simpleType>
                                                            <xs:restriction base="xs:token">
                                                                <xs:enumeration value="YES" />
                                                                <xs:enumeration value="NO" />
                                                            </xs:restriction>
                                                        </xs:simpleType>
                                                    </xs:element>
                                                    <xs:element name="AgeRestriction" minOccurs="0" type="xs:string" />
                                                    <xs:element name="FoundBy">
                                                        <xs:complexType>
                                                            <xs:sequence>
                                                                <xs:element name="Name" type="xs:string" />
                                                                <xs:element name="Address" type="xs:string" />
                                                            </xs:sequence>
                                                        </xs:complexType>
                                                    </xs:element>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                    <xs:attribute name="medId" use="required" />
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== razzuSharma/xml_Projects/main.xml
<?xml version='1.0' encoding='UTF-8'?>
<!-- <!DOCTYPE MedicalStore SYSTEM "main.dtd"> -->
<!-- <MedicalStore xmlns:xs="http://www.w3.org/2001/XMLSchema-instance" xs:noNamespaceSchemaLocation="19031814_russiandoll.xsd"> -->
<MedicalStore>
    <Stock>
        <Name> Bibek Medical Store</Name>
        <Address Continent="Asia">
            <Country> Nepal </Country>
            <City>Damak</City>
            <Street>Gwaldubba STR</Street>
        </Address>
        <Contact CityCode="G024">
            <phoneNum>9817910047</phoneNum>
            <Email>razzusharma008@gmail.com</Email>
        </Contact>
        <Logo></Logo>
    </Stock>

    <MedicineDetails>
        <Medicine medId="md104">
            <Categories>Liquid</Categories>
            <useType>Dropper</useType>
            <MedNames>
                <Name namID="med2001">Gamma Hydroxybutyrate</Name>
                <Manufacturer>Phero Oxpharm</Manufacturer>
                <SideEffects>YES</SideEffects>
                <Availability>YES</Availability>
                <AgeRestriction>YES</AgeRestriction>
                <FoundBy>
                    <Name>Laborit Laboratory</Name>
                    <Address>U.S.A</Address>
                </FoundBy>
            </MedNames>
        </Medicine>
    </MedicineDetails>

    <MedicineDetails>
        <Medicine medId="md204">
            <Categories>Tablet</Categories>
            <useType>Edible</useType>
            <MedNames>
                <Name namID="med3001">Paracetamol</Name>
                <Manufacturer>CFL Pharma</Manufacturer>
                <SideEffects>YES</SideEffects>
                <Availability>YES</Availability>
                <AgeRestriction>NO</AgeRestriction>
                <FoundBy>
                    <Name>Von Mering</Name>
                    <Address>Germany</Address>
                </FoundBy>
            </MedNames>
        </Medicine>
    </MedicineDetails>

    <MedicineDetails>
        <Medicine medId="md304">
            <Categories>Capsules</Categories>
            <useType>Edible</useType>
            <MedNames>
                <Name namID="med4001">Alfacalcidol</Name>
                <Manufacturer>Roche</Manufacturer>
                <SideEffects>YES</SideEffects>
                <Availability>YES</Availability>
                <FoundBy>
                    <Name>Reman Laboratory</Name>
                    <Address>Russia</Address>
                </FoundBy>
            </MedNames>
        </Medicine>
    </MedicineDetails>

    <MedicineDetails>
        <Medicine medId="md404">
            <Categories>Inhalers</Categories>
            <useType>Inhaling</useType>
            <MedNames>
                <Name namID="med5001">Flovent HFA</Name>
                <Manufacturer>GSK pharma</Manufacturer>
                <SideEffects>YES</SideEffects>
                <Availability>YES</Availability>
                <FoundBy>
                    <Name>Deram Laboratory</Name>
                    <Address>Canada</Address>
                </FoundBy>
            </MedNames>
        </Medicine>
    </MedicineDetails>
</MedicalStore>
